/* Journey data: edit freely. c = category key; d = detail bullets shown in the pop-up */
const CAT={r:"Research",s:"Selections & scholarships",c:"Schools & courses",a:"Competitions & awards",l:"Leadership & service"};
const J=[
["2026","r","Machine-learning force fields for HgO on Au(111)","Joint Institute for Nuclear Research (BLTP), INTEREST programme · remote",["Supervised by Dr. Dipayan Sen, co-supervised by Dr. Miroslav Iliaš.","Built an open-source Python/ASE workflow to screen adsorption sites on Au(111), then benchmarked CHGNet and MACE-MP-0 across geometry, uncertainty, vibrations, free energy and Langevin MD.","Reported 65 calculated quantities with full provenance, and five failed calculations as results.","Outcome: first-author manuscript; bridge site lowest in energy (−2.04 eV) but not statistically resolved (uncertainty about 216 meV).","Skills strengthened: Linux automation, scientific Python, atomistic thermodynamics."]],
["2026","r","Undergraduate thesis: QAOA for soft-catheter control","Aswan University · supervisor Dr. Mohamed Gaber",["Formulated multi-actuator trajectory tracking as a QUBO with a numerically verified exact reduction.","Benchmarked classical MPC, simulated annealing, full-parameter QAOA, linear-ramp QAOA and warm-start QAOA on up to 24 qubits.","Extended the study to closed-loop receding-horizon control under simulated hysteresis.","Full write-up on the Research page."]],
["2026","s","MCQST Summer Bachelor Program, TU Munich","Prof. Frank Pollmann's group · topological phases and tensor networks",["Selected to join Prof. Pollmann's group, whose work covers topological phases of matter, symmetry-protected topological order and tensor-network methods.","To my knowledge, the first student from Aswan University selected for a programme of this kind.","I was unable to attend because of mandatory obligations in my home country, and as a final-year student I cannot reapply."]],
["2026","s","ICTP African School of Fundamental Physics, Nairobi","9th Biennial ASP2026 · fully funded scholar",["Admitted from 436 applications across 45 countries (169 participants).","Fully funded scholarship covering attendance; I took part online.","Two weeks with international faculty and a multinational cohort of physics students."]],
["2026","c","MIT iQuHACK","Remote hackathon · MIT iQuISE",["Selected from a large global applicant pool.","Worked on live challenges and attended workshops given by industry sponsors in quantum hardware and software."]],
["2026","l","In Situ Graduate School: Mapping the Upper Nile","IIAS (Leiden), Aswan University, Fakhour Ana foundation · 21–26 April",["Local participant in a mixed team of local and international researchers.","Wrote on the Temple of Kalabsha and the First Cataract, and visited Saluga and Ghazal islands.","Worked in the team of Dr. Aarti Kawlra, Academic Director of Humanities Across Borders."]],
["2025","s","Quantum Education Summit, Barcelona","Catalonia Quantum Academy (ICFO), funded by SPIE · December",["One of only four international students awarded a fully funded scholarship.","Engaged with curriculum materials on quantum education methods and industry skill maps."]],
["2025","s","Ingenii Experiential Quantum Immersion Program","Ambassadorship scholarship · Fall 2025 cohort",["Sole recipient of the Ambassadorship scholarship in my round.","Twelve weeks under Dr. Laia Domingo: quantum machine learning fundamentals and the ingenii-quantum Python library on real datasets.","Innovation Lab projects followed by hackathons."]],
["2025","a","Pan-African Quantum Challenge, error-mitigation track","Africa Quantum Consortium × Aqora · team of five",["Built a stacking ensemble (XGBoost, LSTM-enhanced network, random forest) to correct noisy expectation values.","Trained on 36,450 simulated circuit instances with three noise channels.","Mentor: Hamza Benkadour."]],
["2025","a","First National Quantum Hackathon, Alexandria","Open Quantum Institute, qBraid, Bibliotheca Alexandrina",["Simulated the CO₂–NH₃ reaction relevant to carbon capture.","Optimized the molecules with DFT, mapped the chemistry to qubits, built custom VQE circuits and ran them on IBM quantum hardware with error mitigation.","Presented the solution to an expert panel."]],
["2025","r","Summer school and team project, British University in Egypt","Center for Theoretical Physics · 7–17 July · led by Dr. Amr El-Zant",["Courses: general relativity, cosmology, quantum field theory, quantum computing, physics beyond the Standard Model, quantum machine learning.","Tools: GRTensor II, Garfield++, ROOT, Python, Bayesian inference.","Small team project on alternatives to ΛCDM and the H₀ and σ₈ tensions."]],
["2025","c","IBM Qiskit Global Summer School","IBM Quantum · two weeks",["Quantum simulation and quantum machine learning, from the mathematics to circuits on real hardware.","Lectures by researchers from IBM Quantum and the wider quantum community."]],
["2025","c","Introduction to Plasma and Fusion","Princeton Plasma Physics Laboratory (U.S. DOE) · 10 days",["Theory and instrumentation of plasma and fusion systems, including tokamaks and stellarators.","Live lectures with faculty and representatives of leading plasma institutions."]],
["2025","c","Python for Physics","UC Berkeley · online, with a particle-physics mini course",["Numerical methods, data analysis and simulation in Python, applied directly to my quantum-computing projects."]],
["2025","c","QBronze diploma","QWorld × Open Quantum Institute",["Circuit design in Qiskit, superposition and entanglement, quantum teleportation, superdense coding and Grover's algorithm."]],
["2025","c","Digital Fabrication","Orange Digital Center Egypt",["Onshape CAD, laser cutting and 3D printing.","Built a laser-cut model of a quantum computer and a 3D-printed boron atom, and studied why precise hardware (shielding, cryogenic packaging) matters for coherence."]],
["2025","a","First place, best undergraduate research project of Aswan University","All faculties · also named top student researcher",["Awarded for the perovskite solar-cell project (physics-informed neural network).","Details on the Research page."]],
["2025","a","First place, Desert Research Center training","Marsa Matrouh · with EDRC · team of five",["Our team built an AI prototype to forecast floods, rainfall intensity, groundwater level, salinity and desertification risk for desert communities.","The prototype currently runs on synthetic data and is designed to be connected to real records.","Prize: first place and a 5,000 EGP seed grant."]],
["2025","l","Founder, Masira Advocacy Club","British Council programme · Aswan",["Founded and led a rural youth advocacy club for girls' education.","Authored a policy paper submitted to the Egyptian Ministry of Education."]],
["2024","r","APEX: protective screen for solar panels","With Prof. Ayman El-Amin",["Concept, COMSOL modelling and a working prototype.","Winner of the Nile Innovation Pre-Incubation Competition; proceeding to patent registration.","Full write-up on the Research page."]],
["2024","a","Winner, Nile Innovation Pre-Incubation Competition","Among 50+ applications nationwide · 30,000 EGP",["Funding to build the APEX prototype.","I was later offered further funding to found a company and chose to continue in academic research."]],
["2024","a","Finalist, Innovation Olympics","One of 15 university projects in Egypt",["Reached the final stage with a sustainable-energy innovation."]],
["2024","a","Top 3, national entrepreneurship bootcamp","Tech Start · U.S. Embassy and Amideast",["Developed a venture idea addressing a local challenge in Upper Egypt."]],
["2024","l","Youth Voices, British Council","Advocacy and debate track",["Selected for the advanced advocacy programme: 1 of 30 chosen nationally from 500+ applicants.","Training in policy writing, disability inclusion and gender-based-violence prevention."]],
["2022–24","l","Research Team Leader, Undergraduate Researchers Initiative","Aswan University",["Led a student research team on quantum technologies and mentored junior members.","Set project timelines and ran specialised training sessions."]],
["2022–23","l","Ambassador, Center for Open Science Egypt","Reproducible research",["Led 10+ training sessions for researchers at Egyptian universities."]]
];
const el=(t,c,h)=>{const e=document.createElement(t);if(c)e.className=c;if(h!=null)e.innerHTML=h;return e};
const fl=document.getElementById("fl"),box=document.getElementById("tlx"),dg=document.getElementById("dg");let cur="all";
function draw(){box.innerHTML="";const ys=[...new Set(J.map(x=>x[0]))];
ys.forEach(y=>{const it=J.filter(x=>x[0]===y&&(cur==="all"||x[1]===cur));if(!it.length)return;
const g=el("div","yg rv in");g.append(el("h3","",y));const w=el("div","it");
it.forEach(x=>{const b=el("button","jc",`<span class="k">${CAT[x[1]]}</span><b>${x[2]}</b><em>${x[3]}</em><i>Details</i>`);b.onclick=()=>{dg.innerHTML=`<button class="dx" aria-label="Close" onclick="dg.close()">×</button><span class="k">${CAT[x[1]]} · ${x[0]}</span><h3>${x[2]}</h3><p class="o">${x[3]}</p><ul>${x[4].map(l=>`<li>${l}</li>`).join("")}</ul>`;dg.showModal()};w.append(b)});
g.append(w);box.append(g)})}
[["all","All"],...Object.entries(CAT)].forEach(([k,v])=>{const b=el("button",k==="all"?"on":"",v);b.onclick=()=>{cur=k;[...fl.children].forEach(c=>c.classList.toggle("on",c===b));draw()};fl.append(b)});
dg.addEventListener("click",e=>{if(e.target===dg)dg.close()});draw();
